import type { Metadata } from "next";

import { Inter } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignOutButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { ToasterProvider } from "@/components/providers/toaster.provider";
import { ConfettiProvider } from "@/components/providers/confetti-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      {/* <html lang="en" className="h-full">
      <body
        className={`h-full ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <SignedOut>
        <header className="flex justify-end items-center p-4 gap-4 h-16">
          <SignInButton />
          <SignUpButton>
            <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
              Sign Up
            </button>
          </SignUpButton>
        </header>
      </SignedOut>



        {children}
      </body>
    </html> */}
    <html lang="en">
        <body className={inter.className}>
          <ConfettiProvider/>
          <ToasterProvider/>
          {children}

        </body>
    </html>
    </ClerkProvider>
    
  );
}
